/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // Main narrative pages
    "Introduction",
    "Career-Highlights",
    "Speaking",
    "Community",

    // Work & Projects
    {
      type: "category",
      label: "Work & Projects",
      link: {
        type: "generated-index",
        title: "Work & Projects",
        description:
          "Professional work, side projects, and technical contributions across my career.",
        keywords: ["balena", "projects", "hackathons", "work"],
      },
      collapsed: false,
      items: [
        "Balena",
        "Projects",
        "Hackathons",
        {
          type: "link",
          label: "Mixster",
          description: "Initiative to 'right' the docs for startups.",
          href: "https://mixster.dev/2019/05/24/mixster/",
        },
      ],
    },

    // The Human Side
    {
      type: "category",
      label: "The Human Side",
      link: {
        type: "generated-index",
        title: "Beyond the Code",
        description:
          "The roads not taken, side quests, and what makes me human.",
        keywords: ["multiverse", "side quests", "personal"],
      },
      collapsed: true,
      items: ["Multiverse"],
    },

    // Archive (collapsed by default)
    {
      type: "category",
      label: "Archive",
      link: {
        type: "generated-index",
        title: "Archive",
        description:
          "Historical content preserved for completeness. Earlier talks, communities, and programs.",
        keywords: ["archive", "history", "gsoc"],
      },
      collapsed: true,
      items: [
        "Google Summer of Code",
        "Talks",
        "Conferences",
        "Podcasts",
        "Workshops",
        "Communities",
        "Mentoring",
        "Designs",
        "interview-questions",
      ],
    },
  ],
};

export default sidebars;
