name: Doctor Docs

on:
  schedule:
    - cron: "00 00 * * 1"

  # Runs on each PR
  pull_request:
    branches:
      - "master"
      - 'main'
  # Runs on each push
  push:
    branches:
      - 'main'
      - 'master'


jobs:
  Checking-Docs:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # Run link checker on the generated HTML
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@22134d37a1fff6c2974df9c92a7c7e1e86a08f9c # 1.9.0
        with:
          args: >
            --config ./lychee.toml
            README.md
      
      # Check spelling
      - name: Spelling Checker
        id: spellcheck
        run: |
          npm run test:spellcheck

      - name: Create Issue From File
        if: |
          github.event_name != 'pull_request' &&
          env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: good-first-issue, automated issue